---
abstract: 'initialize bot instance with YAML config'
author:
  - 'Takatoshi Kitano <kitano.tk {at} gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-WithConfig
no_index:
  directory:
    - inc
    - t
requires:
  Bot::BasicBot::Pluggable: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
